version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: talentvault_db
    restart: always
    volumes:
      - data:/var/lib/mysql
    env_file:
      - ../.env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  backend:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: talentvault_backend
    command: sh -c "python3 manage.py migrate --noinput &&  python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ..:/app
    env_file:
      - ../.env
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  data: