# Generated by Django 5.1.6 on 2025-03-03 18:26

import storages.backends.azure_storage
import vault.utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=storages.backends.azure_storage.AzureStorage(azure_container='talentvault-blobcontainer', connection_string='DefaultEndpointsProtocol=https;AccountName=talentvault;AccountKey=YEI28ls92ChZP5J6EUBINpGP4VbPDN0URfZXpIPlb234GlzJRYjM7oj1pPFF6zoKpnEsDuUHjOA5+AStMvqJDg==;EndpointSuffix=core.windows.net'), upload_to=vault.utils.dynamic_storage.get_upload_path),
        ),
    ]
