# Generated by Django 5.1.6 on 2025-03-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.IntegerField()),
                ('department_id', models.IntegerField(choices=[(1, 'Engineering'), (2, 'Sales'), (3, 'Marketing'), (4, 'Human Resources'), (5, 'Finance'), (6, 'Operations')])),
                ('resume', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
