# Generated by Django 5.1.6 on 2025-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='department_id',
            field=models.IntegerField(choices=[(1, 'Engineering'), (2, 'Sales'), (3, 'Marketing'), (4, 'Human Resources'), (5, 'Finance'), (6, 'Operations')], db_index=True),
        ),
    ]
