# Generated by Django 5.1.6 on 2025-03-01 13:36

import django.core.files.storage
import vault.utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_candidate_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/app/media'), upload_to=vault.utils.dynamic_storage.get_upload_path),
        ),
    ]
