# Generated by Django 5.1.6 on 2025-03-02 12:23

import storages.backends.s3
import vault.utils.dynamic_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(access_key='AKIAVFPEU25EE7VR24CI', bucket_name='talentvaultbucket', region_name='us-east-1', secret_key='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'), upload_to=vault.utils.dynamic_storage.get_upload_path),
        ),
    ]
